### ISSUE TITLE
Key management improvements

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/OzoneWalletIOS#185]
Add error message when encrypted key is entered incorrectly.
If the key is complete but one letter is wrong, it will crash the app.

~~Add ability to export NEP6 file from login screen.~~

~~Enable itunes file sharing for NEP6 extraction~~

**Comment by saltyskip** [comment]
Will not add ability to export from login screen, instead we have two additional recovery measure. Adding the export from home page will make users confused/feel insecure because there is an export keys option available without authentication.

Instead we add two improvements

1) Enable file sharing via itunes to export nep6
2) Fallback on manual password entry if keychain has become corrupted somehow
